// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AFormItemRest: typeof import('ant-design-vue/es')['FormItemRest']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PlaceDepartment: typeof import('./src/components/PlaceHeader/PlaceDepartment.vue')['default']
    PlaceName: typeof import('./src/components/PlaceHeader/PlaceName.vue')['default']
    PlaceScheduling: typeof import('./src/components/PlaceHeader/PlaceScheduling.vue')['default']
    ProjectName: typeof import('./src/components/PlaceProject/ProjectName.vue')['default']
    ProjectPhoto: typeof import('./src/components/PlaceProject/ProjectPhoto.vue')['default']
    ProjectVideo: typeof import('./src/components/PlaceProject/ProjectVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
