# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'media_three_text_image_video_edit.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGroupBox, QLabel, QLineEdit, QPlainTextEdit,
    QPushButton, QSizePolicy, QSpinBox, QWidget)

class Ui_Dialog_media_three_text_image_video_edit(object):
    def setupUi(self, Dialog_media_three_text_image_video_edit):
        if not Dialog_media_three_text_image_video_edit.objectName():
            Dialog_media_three_text_image_video_edit.setObjectName(u"Dialog_media_three_text_image_video_edit")
        Dialog_media_three_text_image_video_edit.setWindowModality(Qt.ApplicationModal)
        Dialog_media_three_text_image_video_edit.resize(480, 540)
        self.pushButton = QPushButton(Dialog_media_three_text_image_video_edit)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 460, 121, 41))
        self.groupBox_three = QGroupBox(Dialog_media_three_text_image_video_edit)
        self.groupBox_three.setObjectName(u"groupBox_three")
        self.groupBox_three.setGeometry(QRect(10, 20, 461, 421))
        self.groupBox_font_three = QGroupBox(self.groupBox_three)
        self.groupBox_font_three.setObjectName(u"groupBox_font_three")
        self.groupBox_font_three.setGeometry(QRect(0, 110, 461, 81))
        self.comboBox_font_color_three = QComboBox(self.groupBox_font_three)
        self.comboBox_font_color_three.setObjectName(u"comboBox_font_color_three")
        self.comboBox_font_color_three.setGeometry(QRect(190, 30, 111, 31))
        self.comboBox_font_size_three = QComboBox(self.groupBox_font_three)
        self.comboBox_font_size_three.setObjectName(u"comboBox_font_size_three")
        self.comboBox_font_size_three.setGeometry(QRect(340, 30, 111, 31))
        self.label_13 = QLabel(self.groupBox_font_three)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(310, 30, 31, 31))
        self.label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_14 = QLabel(self.groupBox_font_three)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 30, 31, 31))
        self.label_14.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.comboBox_font_three = QComboBox(self.groupBox_font_three)
        self.comboBox_font_three.setObjectName(u"comboBox_font_three")
        self.comboBox_font_three.setGeometry(QRect(40, 30, 111, 31))
        self.label_18 = QLabel(self.groupBox_font_three)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(160, 30, 31, 31))
        self.label_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pushButton_media_three = QPushButton(self.groupBox_three)
        self.pushButton_media_three.setObjectName(u"pushButton_media_three")
        self.pushButton_media_three.setGeometry(QRect(390, 30, 71, 61))
        self.plainTextEdit_media_path_three = QPlainTextEdit(self.groupBox_three)
        self.plainTextEdit_media_path_three.setObjectName(u"plainTextEdit_media_path_three")
        self.plainTextEdit_media_path_three.setGeometry(QRect(0, 30, 391, 61))
        self.groupBox_coordination_three = QGroupBox(self.groupBox_three)
        self.groupBox_coordination_three.setObjectName(u"groupBox_coordination_three")
        self.groupBox_coordination_three.setGeometry(QRect(0, 230, 461, 181))
        self.label_24 = QLabel(self.groupBox_coordination_three)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 80, 31, 31))
        self.label_24.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_2 = QLabel(self.groupBox_coordination_three)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 30, 31, 31))
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_media_longitude = QLineEdit(self.groupBox_coordination_three)
        self.lineEdit_media_longitude.setObjectName(u"lineEdit_media_longitude")
        self.lineEdit_media_longitude.setGeometry(QRect(40, 30, 111, 31))
        self.label_3 = QLabel(self.groupBox_coordination_three)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(310, 30, 31, 31))
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_media_latitude = QLineEdit(self.groupBox_coordination_three)
        self.lineEdit_media_latitude.setObjectName(u"lineEdit_media_latitude")
        self.lineEdit_media_latitude.setGeometry(QRect(190, 30, 111, 31))
        self.lineEdit_media_altitude = QLineEdit(self.groupBox_coordination_three)
        self.lineEdit_media_altitude.setObjectName(u"lineEdit_media_altitude")
        self.lineEdit_media_altitude.setGeometry(QRect(340, 30, 111, 31))
        self.label_5 = QLabel(self.groupBox_coordination_three)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(160, 30, 31, 31))
        self.label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_30 = QLabel(self.groupBox_coordination_three)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(310, 80, 31, 31))
        self.label_30.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_23 = QLabel(self.groupBox_coordination_three)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(160, 80, 31, 31))
        self.label_23.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_media_3d_tile = QCheckBox(self.groupBox_coordination_three)
        self.checkBox_media_3d_tile.setObjectName(u"checkBox_media_3d_tile")
        self.checkBox_media_3d_tile.setGeometry(QRect(280, 130, 51, 31))
        self.pushButton_get_position = QPushButton(self.groupBox_coordination_three)
        self.pushButton_get_position.setObjectName(u"pushButton_get_position")
        self.pushButton_get_position.setGeometry(QRect(40, 130, 111, 31))
        self.spinBox_media_3d_width = QSpinBox(self.groupBox_coordination_three)
        self.spinBox_media_3d_width.setObjectName(u"spinBox_media_3d_width")
        self.spinBox_media_3d_width.setGeometry(QRect(40, 80, 111, 31))
        self.spinBox_media_3d_width.setMinimum(1)
        self.spinBox_media_3d_width.setMaximum(6400000)
        self.spinBox_media_3d_width.setValue(100)
        self.spinBox_media_3d_height = QSpinBox(self.groupBox_coordination_three)
        self.spinBox_media_3d_height.setObjectName(u"spinBox_media_3d_height")
        self.spinBox_media_3d_height.setGeometry(QRect(190, 80, 111, 31))
        self.spinBox_media_3d_height.setMinimum(1)
        self.spinBox_media_3d_height.setMaximum(6400000)
        self.spinBox_media_3d_height.setValue(100)
        self.spinBox_media_3d_depth = QSpinBox(self.groupBox_coordination_three)
        self.spinBox_media_3d_depth.setObjectName(u"spinBox_media_3d_depth")
        self.spinBox_media_3d_depth.setGeometry(QRect(340, 80, 111, 31))
        self.spinBox_media_3d_depth.setMinimum(1)
        self.spinBox_media_3d_depth.setMaximum(99999)
        self.spinBox_media_3d_depth.setValue(1)
        self.checkBox_media_3d_always_show = QCheckBox(self.groupBox_coordination_three)
        self.checkBox_media_3d_always_show.setObjectName(u"checkBox_media_3d_always_show")
        self.checkBox_media_3d_always_show.setGeometry(QRect(190, 130, 51, 31))

        self.retranslateUi(Dialog_media_three_text_image_video_edit)

        QMetaObject.connectSlotsByName(Dialog_media_three_text_image_video_edit)
    # setupUi

    def retranslateUi(self, Dialog_media_three_text_image_video_edit):
        Dialog_media_three_text_image_video_edit.setWindowTitle(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"Dialog", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u4fdd\u5b58", None))
        self.groupBox_three.setTitle(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"3D\u6587\u5b57\u3001\u56fe\u7247\u3001\u89c6\u9891\u8bbe\u7f6e", None))
        self.groupBox_font_three.setTitle(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"3D\u5b57\u4f53", None))
        self.label_13.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u5b57\u53f7", None))
        self.label_14.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u5b57\u4f53", None))
        self.label_18.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u989c\u8272", None))
        self.pushButton_media_three.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u6d4f\u89c8\u6587\u4ef6", None))
        self.plainTextEdit_media_path_three.setPlaceholderText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u6587\u672c\u5185\u5bb9\u3001\u56fe\u7247\u8def\u5f84\u6216\u89c6\u9891\u8def\u5f84", None))
        self.groupBox_coordination_three.setTitle(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"3D\u5750\u6807\u8bbe\u7f6e", None))
        self.label_24.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u5bbd\u5ea6", None))
        self.label_2.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u7ecf\u5ea6", None))
        self.lineEdit_media_longitude.setPlaceholderText("")
        self.label_3.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u6d77\u62d4", None))
        self.lineEdit_media_latitude.setPlaceholderText("")
        self.lineEdit_media_altitude.setPlaceholderText("")
        self.label_5.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u7eac\u5ea6", None))
        self.label_30.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u7eb5\u6df1", None))
        self.label_23.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u9ad8\u5ea6", None))
        self.checkBox_media_3d_tile.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u5e73\u5730", None))
        self.pushButton_get_position.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u83b7\u53d6\u5750\u6807", None))
        self.checkBox_media_3d_always_show.setText(QCoreApplication.translate("Dialog_media_three_text_image_video_edit", u"\u7559\u5b58", None))
    # retranslateUi

