# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'media_screen_text_image_video_edit.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDialog, QDoubleSpinBox, QGroupBox, QLabel,
    QPlainTextEdit, QPushButton, QSizePolicy, QSpinBox,
    QWidget)

class Ui_Dialog_media_screen_text_image_video_edit(object):
    def setupUi(self, Dialog_media_screen_text_image_video_edit):
        if not Dialog_media_screen_text_image_video_edit.objectName():
            Dialog_media_screen_text_image_video_edit.setObjectName(u"Dialog_media_screen_text_image_video_edit")
        Dialog_media_screen_text_image_video_edit.setWindowModality(Qt.ApplicationModal)
        Dialog_media_screen_text_image_video_edit.resize(480, 540)
        self.groupBox_screen = QGroupBox(Dialog_media_screen_text_image_video_edit)
        self.groupBox_screen.setObjectName(u"groupBox_screen")
        self.groupBox_screen.setGeometry(QRect(10, 10, 461, 411))
        self.pushButton_media = QPushButton(self.groupBox_screen)
        self.pushButton_media.setObjectName(u"pushButton_media")
        self.pushButton_media.setGeometry(QRect(390, 30, 71, 61))
        self.plainTextEdit_media_path = QPlainTextEdit(self.groupBox_screen)
        self.plainTextEdit_media_path.setObjectName(u"plainTextEdit_media_path")
        self.plainTextEdit_media_path.setGeometry(QRect(0, 30, 391, 61))
        self.groupBox_screen_setting = QGroupBox(self.groupBox_screen)
        self.groupBox_screen_setting.setObjectName(u"groupBox_screen_setting")
        self.groupBox_screen_setting.setGeometry(QRect(0, 230, 461, 171))
        self.label_6 = QLabel(self.groupBox_screen_setting)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 30, 31, 31))
        self.label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_32 = QLabel(self.groupBox_screen_setting)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 30, 31, 31))
        self.label_32.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_7 = QLabel(self.groupBox_screen_setting)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 70, 31, 31))
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.spinBox_media_2d_height = QSpinBox(self.groupBox_screen_setting)
        self.spinBox_media_2d_height.setObjectName(u"spinBox_media_2d_height")
        self.spinBox_media_2d_height.setGeometry(QRect(40, 70, 111, 31))
        self.spinBox_media_2d_height.setAlignment(Qt.AlignCenter)
        self.spinBox_media_2d_height.setMinimum(1)
        self.spinBox_media_2d_height.setMaximum(100)
        self.spinBox_media_2d_height.setValue(50)
        self.spinBox_media_2d_top = QSpinBox(self.groupBox_screen_setting)
        self.spinBox_media_2d_top.setObjectName(u"spinBox_media_2d_top")
        self.spinBox_media_2d_top.setGeometry(QRect(190, 30, 111, 31))
        self.spinBox_media_2d_top.setAlignment(Qt.AlignCenter)
        self.spinBox_media_2d_top.setMinimum(0)
        self.spinBox_media_2d_top.setMaximum(100)
        self.spinBox_media_2d_top.setValue(50)
        self.label_31 = QLabel(self.groupBox_screen_setting)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(160, 70, 31, 31))
        self.label_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.spinBox_media_2d_left = QSpinBox(self.groupBox_screen_setting)
        self.spinBox_media_2d_left.setObjectName(u"spinBox_media_2d_left")
        self.spinBox_media_2d_left.setGeometry(QRect(190, 70, 111, 31))
        self.spinBox_media_2d_left.setAlignment(Qt.AlignCenter)
        self.spinBox_media_2d_left.setMinimum(0)
        self.spinBox_media_2d_left.setMaximum(100)
        self.spinBox_media_2d_left.setValue(50)
        self.spinBox_media_2d_width = QSpinBox(self.groupBox_screen_setting)
        self.spinBox_media_2d_width.setObjectName(u"spinBox_media_2d_width")
        self.spinBox_media_2d_width.setGeometry(QRect(40, 30, 111, 31))
        self.spinBox_media_2d_width.setAlignment(Qt.AlignCenter)
        self.spinBox_media_2d_width.setMinimum(1)
        self.spinBox_media_2d_width.setMaximum(100)
        self.spinBox_media_2d_width.setValue(50)
        self.checkBox_media_2d_to_three_after_display = QCheckBox(self.groupBox_screen_setting)
        self.checkBox_media_2d_to_three_after_display.setObjectName(u"checkBox_media_2d_to_three_after_display")
        self.checkBox_media_2d_to_three_after_display.setGeometry(QRect(190, 120, 111, 31))
        self.checkBox_media_2d_to_side_after_display = QCheckBox(self.groupBox_screen_setting)
        self.checkBox_media_2d_to_side_after_display.setObjectName(u"checkBox_media_2d_to_side_after_display")
        self.checkBox_media_2d_to_side_after_display.setEnabled(False)
        self.checkBox_media_2d_to_side_after_display.setGeometry(QRect(340, 120, 111, 31))
        self.doubleSpinBox_media_2d_opacity = QDoubleSpinBox(self.groupBox_screen_setting)
        self.doubleSpinBox_media_2d_opacity.setObjectName(u"doubleSpinBox_media_2d_opacity")
        self.doubleSpinBox_media_2d_opacity.setGeometry(QRect(340, 30, 111, 31))
        self.doubleSpinBox_media_2d_opacity.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_media_2d_opacity.setDecimals(2)
        self.doubleSpinBox_media_2d_opacity.setMaximum(1.000000000000000)
        self.doubleSpinBox_media_2d_opacity.setSingleStep(0.100000000000000)
        self.doubleSpinBox_media_2d_opacity.setStepType(QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_media_2d_opacity.setValue(0.850000000000000)
        self.label_8 = QLabel(self.groupBox_screen_setting)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(310, 30, 31, 31))
        self.label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.checkBox_media_2d_full_screen = QCheckBox(self.groupBox_screen_setting)
        self.checkBox_media_2d_full_screen.setObjectName(u"checkBox_media_2d_full_screen")
        self.checkBox_media_2d_full_screen.setGeometry(QRect(40, 120, 71, 31))
        self.checkBox_media_2d_set_center = QCheckBox(self.groupBox_screen_setting)
        self.checkBox_media_2d_set_center.setObjectName(u"checkBox_media_2d_set_center")
        self.checkBox_media_2d_set_center.setGeometry(QRect(340, 80, 111, 31))
        self.groupBox_screen_font = QGroupBox(self.groupBox_screen)
        self.groupBox_screen_font.setObjectName(u"groupBox_screen_font")
        self.groupBox_screen_font.setGeometry(QRect(0, 110, 461, 81))
        self.comboBox_font_color = QComboBox(self.groupBox_screen_font)
        self.comboBox_font_color.setObjectName(u"comboBox_font_color")
        self.comboBox_font_color.setGeometry(QRect(190, 30, 111, 31))
        self.comboBox_font_size = QComboBox(self.groupBox_screen_font)
        self.comboBox_font_size.setObjectName(u"comboBox_font_size")
        self.comboBox_font_size.setGeometry(QRect(340, 30, 111, 31))
        self.label_11 = QLabel(self.groupBox_screen_font)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(310, 30, 31, 31))
        self.label_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_10 = QLabel(self.groupBox_screen_font)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 30, 31, 31))
        self.label_10.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.comboBox_font = QComboBox(self.groupBox_screen_font)
        self.comboBox_font.setObjectName(u"comboBox_font")
        self.comboBox_font.setGeometry(QRect(40, 30, 111, 31))
        self.label_17 = QLabel(self.groupBox_screen_font)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(160, 30, 31, 31))
        self.label_17.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pushButton = QPushButton(Dialog_media_screen_text_image_video_edit)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 460, 121, 41))

        self.retranslateUi(Dialog_media_screen_text_image_video_edit)

        QMetaObject.connectSlotsByName(Dialog_media_screen_text_image_video_edit)
    # setupUi

    def retranslateUi(self, Dialog_media_screen_text_image_video_edit):
        Dialog_media_screen_text_image_video_edit.setWindowTitle(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"Dialog", None))
        self.groupBox_screen.setTitle(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"2D\u6587\u5b57\u3001\u56fe\u7247\u3001\u89c6\u9891\u8bbe\u7f6e", None))
        self.pushButton_media.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u6d4f\u89c8\u6587\u4ef6", None))
        self.plainTextEdit_media_path.setPlaceholderText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u6587\u672c\u5185\u5bb9\u3001\u56fe\u7247\u8def\u5f84\u6216\u89c6\u9891\u8def\u5f84\uff0c", None))
        self.groupBox_screen_setting.setTitle(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"2D\u8bbe\u7f6e", None))
        self.label_6.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"TOP", None))
        self.label_32.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u5bbd\u5ea6", None))
        self.label_7.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u9ad8\u5ea6", None))
        self.label_31.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"LEFT", None))
        self.checkBox_media_2d_to_three_after_display.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u7ed3\u675f\u540e\u52a0\u51653D", None))
        self.checkBox_media_2d_to_side_after_display.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u7ed3\u675f\u540e\u4fdd\u7559", None))
        self.label_8.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u900f\u660e", None))
        self.checkBox_media_2d_full_screen.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u5168\u5c4f\u663e\u793a", None))
        self.checkBox_media_2d_set_center.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u5c45\u4e2d\u663e\u793a", None))
        self.groupBox_screen_font.setTitle(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u5b57\u4f53", None))
        self.label_11.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u5b57\u53f7", None))
        self.label_10.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u5b57\u4f53", None))
        self.label_17.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u989c\u8272", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog_media_screen_text_image_video_edit", u"\u4fdd\u5b58", None))
    # retranslateUi

