# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'media_three_overlay_edit.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QGroupBox, QLabel,
    QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy,
    QWidget)

class Ui_Dialog_media_three_overlay_edit(object):
    def setupUi(self, Dialog_media_three_overlay_edit):
        if not Dialog_media_three_overlay_edit.objectName():
            Dialog_media_three_overlay_edit.setObjectName(u"Dialog_media_three_overlay_edit")
        Dialog_media_three_overlay_edit.setWindowModality(Qt.ApplicationModal)
        Dialog_media_three_overlay_edit.resize(480, 540)
        self.pushButton = QPushButton(Dialog_media_three_overlay_edit)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 460, 121, 41))
        self.groupBox_three = QGroupBox(Dialog_media_three_overlay_edit)
        self.groupBox_three.setObjectName(u"groupBox_three")
        self.groupBox_three.setGeometry(QRect(10, 20, 461, 421))
        self.pushButton_media_three = QPushButton(self.groupBox_three)
        self.pushButton_media_three.setObjectName(u"pushButton_media_three")
        self.pushButton_media_three.setGeometry(QRect(390, 30, 71, 61))
        self.plainTextEdit_media_path_three = QPlainTextEdit(self.groupBox_three)
        self.plainTextEdit_media_path_three.setObjectName(u"plainTextEdit_media_path_three")
        self.plainTextEdit_media_path_three.setGeometry(QRect(0, 30, 391, 61))
        self.groupBox_media_overlay = QGroupBox(self.groupBox_three)
        self.groupBox_media_overlay.setObjectName(u"groupBox_media_overlay")
        self.groupBox_media_overlay.setGeometry(QRect(0, 140, 461, 271))
        self.lineEdit_media_ground_overlay_lon_1 = QLineEdit(self.groupBox_media_overlay)
        self.lineEdit_media_ground_overlay_lon_1.setObjectName(u"lineEdit_media_ground_overlay_lon_1")
        self.lineEdit_media_ground_overlay_lon_1.setGeometry(QRect(50, 30, 111, 31))
        self.label_15 = QLabel(self.groupBox_media_overlay)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(180, 30, 31, 31))
        self.label_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_media_ground_overlay_lat_1 = QLineEdit(self.groupBox_media_overlay)
        self.lineEdit_media_ground_overlay_lat_1.setObjectName(u"lineEdit_media_ground_overlay_lat_1")
        self.lineEdit_media_ground_overlay_lat_1.setGeometry(QRect(220, 30, 111, 31))
        self.label_16 = QLabel(self.groupBox_media_overlay)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 30, 31, 31))
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_media_ground_overlay_lon_2 = QLineEdit(self.groupBox_media_overlay)
        self.lineEdit_media_ground_overlay_lon_2.setObjectName(u"lineEdit_media_ground_overlay_lon_2")
        self.lineEdit_media_ground_overlay_lon_2.setGeometry(QRect(50, 80, 111, 31))
        self.label_20 = QLabel(self.groupBox_media_overlay)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(180, 80, 31, 31))
        self.label_20.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_media_ground_overlay_lat_2 = QLineEdit(self.groupBox_media_overlay)
        self.lineEdit_media_ground_overlay_lat_2.setObjectName(u"lineEdit_media_ground_overlay_lat_2")
        self.lineEdit_media_ground_overlay_lat_2.setGeometry(QRect(220, 80, 111, 31))
        self.label_22 = QLabel(self.groupBox_media_overlay)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 80, 31, 31))
        self.label_22.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_media_ground_overlay_lat_3 = QLineEdit(self.groupBox_media_overlay)
        self.lineEdit_media_ground_overlay_lat_3.setObjectName(u"lineEdit_media_ground_overlay_lat_3")
        self.lineEdit_media_ground_overlay_lat_3.setGeometry(QRect(220, 130, 111, 31))
        self.label_26 = QLabel(self.groupBox_media_overlay)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(180, 130, 31, 31))
        self.label_26.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_27 = QLabel(self.groupBox_media_overlay)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 130, 31, 31))
        self.label_27.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_media_ground_overlay_lon_3 = QLineEdit(self.groupBox_media_overlay)
        self.lineEdit_media_ground_overlay_lon_3.setObjectName(u"lineEdit_media_ground_overlay_lon_3")
        self.lineEdit_media_ground_overlay_lon_3.setGeometry(QRect(50, 130, 111, 31))
        self.lineEdit_media_ground_overlay_lon_4 = QLineEdit(self.groupBox_media_overlay)
        self.lineEdit_media_ground_overlay_lon_4.setObjectName(u"lineEdit_media_ground_overlay_lon_4")
        self.lineEdit_media_ground_overlay_lon_4.setGeometry(QRect(50, 180, 111, 31))
        self.label_28 = QLabel(self.groupBox_media_overlay)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 180, 31, 31))
        self.label_28.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_29 = QLabel(self.groupBox_media_overlay)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(180, 180, 31, 31))
        self.label_29.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_media_ground_overlay_lat_4 = QLineEdit(self.groupBox_media_overlay)
        self.lineEdit_media_ground_overlay_lat_4.setObjectName(u"lineEdit_media_ground_overlay_lat_4")
        self.lineEdit_media_ground_overlay_lat_4.setGeometry(QRect(220, 180, 111, 31))
        self.pushButton_get_position_ground_overlay_1 = QPushButton(self.groupBox_media_overlay)
        self.pushButton_get_position_ground_overlay_1.setObjectName(u"pushButton_get_position_ground_overlay_1")
        self.pushButton_get_position_ground_overlay_1.setGeometry(QRect(350, 30, 101, 31))
        self.pushButton_get_position_ground_overlay_2 = QPushButton(self.groupBox_media_overlay)
        self.pushButton_get_position_ground_overlay_2.setObjectName(u"pushButton_get_position_ground_overlay_2")
        self.pushButton_get_position_ground_overlay_2.setGeometry(QRect(350, 80, 101, 31))
        self.pushButton_get_position_ground_overlay_3 = QPushButton(self.groupBox_media_overlay)
        self.pushButton_get_position_ground_overlay_3.setObjectName(u"pushButton_get_position_ground_overlay_3")
        self.pushButton_get_position_ground_overlay_3.setGeometry(QRect(350, 130, 101, 31))
        self.pushButton_get_position_ground_overlay_4 = QPushButton(self.groupBox_media_overlay)
        self.pushButton_get_position_ground_overlay_4.setObjectName(u"pushButton_get_position_ground_overlay_4")
        self.pushButton_get_position_ground_overlay_4.setGeometry(QRect(350, 180, 101, 31))
        self.pushButton_get_position_ground_overlay = QPushButton(self.groupBox_media_overlay)
        self.pushButton_get_position_ground_overlay.setObjectName(u"pushButton_get_position_ground_overlay")
        self.pushButton_get_position_ground_overlay.setGeometry(QRect(350, 230, 101, 31))

        self.retranslateUi(Dialog_media_three_overlay_edit)

        QMetaObject.connectSlotsByName(Dialog_media_three_overlay_edit)
    # setupUi

    def retranslateUi(self, Dialog_media_three_overlay_edit):
        Dialog_media_three_overlay_edit.setWindowTitle(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u5730\u7403\u53e0\u52a0\u5c42", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u4fdd\u5b58", None))
        self.groupBox_three.setTitle(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u5730\u7403\u53e0\u52a0\u5c42\u8bbe\u7f6e", None))
        self.pushButton_media_three.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u6d4f\u89c8\u6587\u4ef6", None))
        self.plainTextEdit_media_path_three.setPlaceholderText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u53e0\u52a0\u5c42\u56fe\u7247\u8def\u5f84", None))
        self.groupBox_media_overlay.setTitle(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u5730\u7403\u53e0\u52a0\u5c42", None))
        self.lineEdit_media_ground_overlay_lon_1.setPlaceholderText("")
        self.label_15.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u7eac\u5ea61", None))
        self.lineEdit_media_ground_overlay_lat_1.setPlaceholderText("")
        self.label_16.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u7ecf\u5ea61", None))
        self.lineEdit_media_ground_overlay_lon_2.setPlaceholderText("")
        self.label_20.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u7eac\u5ea62", None))
        self.lineEdit_media_ground_overlay_lat_2.setPlaceholderText("")
        self.label_22.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u7ecf\u5ea62", None))
        self.lineEdit_media_ground_overlay_lat_3.setPlaceholderText("")
        self.label_26.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u7eac\u5ea63", None))
        self.label_27.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u7ecf\u5ea63", None))
        self.lineEdit_media_ground_overlay_lon_3.setPlaceholderText("")
        self.lineEdit_media_ground_overlay_lon_4.setPlaceholderText("")
        self.label_28.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u7ecf\u5ea64", None))
        self.label_29.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u7eac\u5ea64", None))
        self.lineEdit_media_ground_overlay_lat_4.setPlaceholderText("")
        self.pushButton_get_position_ground_overlay_1.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u83b7\u53d6\u5750\u6807 1", None))
        self.pushButton_get_position_ground_overlay_2.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u83b7\u53d6\u5750\u6807 2", None))
        self.pushButton_get_position_ground_overlay_3.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u83b7\u53d6\u5750\u6807 3", None))
        self.pushButton_get_position_ground_overlay_4.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u83b7\u53d6\u5750\u6807 4", None))
        self.pushButton_get_position_ground_overlay.setText(QCoreApplication.translate("Dialog_media_three_overlay_edit", u"\u83b7\u53d6\u5750\u6807 \u603b", None))
    # retranslateUi

