# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'subtitle_action_edit.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QDoubleSpinBox, QGroupBox, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QSpinBox, QWidget)

class Ui_Dialog_subtitle_action_edit(object):
    def setupUi(self, Dialog_subtitle_action_edit):
        if not Dialog_subtitle_action_edit.objectName():
            Dialog_subtitle_action_edit.setObjectName(u"Dialog_subtitle_action_edit")
        Dialog_subtitle_action_edit.setWindowModality(Qt.ApplicationModal)
        Dialog_subtitle_action_edit.resize(700, 560)
        Dialog_subtitle_action_edit.setMinimumSize(QSize(700, 0))
        Dialog_subtitle_action_edit.setMaximumSize(QSize(700, 750))
        self.pushButton = QPushButton(Dialog_subtitle_action_edit)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(280, 510, 121, 31))
        self.groupBox_suntitle_action = QGroupBox(Dialog_subtitle_action_edit)
        self.groupBox_suntitle_action.setObjectName(u"groupBox_suntitle_action")
        self.groupBox_suntitle_action.setGeometry(QRect(20, 20, 331, 71))
        self.groupBox_suntitle_action.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.comboBox_fly_type = QComboBox(self.groupBox_suntitle_action)
        self.comboBox_fly_type.setObjectName(u"comboBox_fly_type")
        self.comboBox_fly_type.setGeometry(QRect(40, 30, 111, 31))
        self.label_12 = QLabel(self.groupBox_suntitle_action)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 30, 31, 31))
        self.label_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.doubleSpinBox_fly_speed = QDoubleSpinBox(self.groupBox_suntitle_action)
        self.doubleSpinBox_fly_speed.setObjectName(u"doubleSpinBox_fly_speed")
        self.doubleSpinBox_fly_speed.setGeometry(QRect(210, 30, 111, 31))
        self.doubleSpinBox_fly_speed.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_fly_speed.setDecimals(1)
        self.doubleSpinBox_fly_speed.setMinimum(0.100000000000000)
        self.doubleSpinBox_fly_speed.setValue(1.000000000000000)
        self.label_14 = QLabel(self.groupBox_suntitle_action)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(180, 30, 31, 31))
        self.label_14.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_info = QLabel(Dialog_subtitle_action_edit)
        self.label_info.setObjectName(u"label_info")
        self.label_info.setGeometry(QRect(20, 470, 661, 21))
        self.label_info.setAlignment(Qt.AlignCenter)
        self.groupBox_heading_tilt_view = QGroupBox(Dialog_subtitle_action_edit)
        self.groupBox_heading_tilt_view.setObjectName(u"groupBox_heading_tilt_view")
        self.groupBox_heading_tilt_view.setGeometry(QRect(20, 250, 661, 71))
        self.lineEdit_tilt = QLineEdit(self.groupBox_heading_tilt_view)
        self.lineEdit_tilt.setObjectName(u"lineEdit_tilt")
        self.lineEdit_tilt.setGeometry(QRect(210, 30, 111, 31))
        self.label_38 = QLabel(self.groupBox_heading_tilt_view)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(180, 30, 31, 31))
        self.label_38.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_37 = QLabel(self.groupBox_heading_tilt_view)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 30, 31, 31))
        self.label_37.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_heading = QLineEdit(self.groupBox_heading_tilt_view)
        self.lineEdit_heading.setObjectName(u"lineEdit_heading")
        self.lineEdit_heading.setGeometry(QRect(40, 30, 111, 31))
        self.pushButton_get_heading_tilt = QPushButton(self.groupBox_heading_tilt_view)
        self.pushButton_get_heading_tilt.setObjectName(u"pushButton_get_heading_tilt")
        self.pushButton_get_heading_tilt.setGeometry(QRect(540, 30, 111, 31))
        self.groupBox_screen_action = QGroupBox(Dialog_subtitle_action_edit)
        self.groupBox_screen_action.setObjectName(u"groupBox_screen_action")
        self.groupBox_screen_action.setGeometry(QRect(20, 340, 661, 111))
        self.label_43 = QLabel(self.groupBox_screen_action)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(180, 70, 31, 31))
        self.label_43.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_target_end_x = QLineEdit(self.groupBox_screen_action)
        self.lineEdit_target_end_x.setObjectName(u"lineEdit_target_end_x")
        self.lineEdit_target_end_x.setGeometry(QRect(210, 30, 111, 31))
        self.lineEdit_target_end_y = QLineEdit(self.groupBox_screen_action)
        self.lineEdit_target_end_y.setObjectName(u"lineEdit_target_end_y")
        self.lineEdit_target_end_y.setGeometry(QRect(210, 70, 111, 31))
        self.label_44 = QLabel(self.groupBox_screen_action)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 30, 31, 31))
        self.label_44.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_45 = QLabel(self.groupBox_screen_action)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(180, 30, 31, 31))
        self.label_45.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_target_start_y = QLineEdit(self.groupBox_screen_action)
        self.lineEdit_target_start_y.setObjectName(u"lineEdit_target_start_y")
        self.lineEdit_target_start_y.setGeometry(QRect(40, 70, 111, 31))
        self.label_46 = QLabel(self.groupBox_screen_action)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 70, 31, 31))
        self.label_46.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_target_start_x = QLineEdit(self.groupBox_screen_action)
        self.lineEdit_target_start_x.setObjectName(u"lineEdit_target_start_x")
        self.lineEdit_target_start_x.setGeometry(QRect(40, 30, 111, 31))
        self.spinBox_slide_speed = QSpinBox(self.groupBox_screen_action)
        self.spinBox_slide_speed.setObjectName(u"spinBox_slide_speed")
        self.spinBox_slide_speed.setGeometry(QRect(380, 30, 111, 31))
        self.spinBox_slide_speed.setAlignment(Qt.AlignCenter)
        self.spinBox_slide_speed.setMaximum(32)
        self.spinBox_slide_speed.setValue(3)
        self.label_15 = QLabel(self.groupBox_screen_action)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(350, 30, 31, 31))
        self.label_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pushButton_get_screen_coordination = QPushButton(self.groupBox_screen_action)
        self.pushButton_get_screen_coordination.setObjectName(u"pushButton_get_screen_coordination")
        self.pushButton_get_screen_coordination.setGeometry(QRect(540, 30, 111, 71))
        self.label_16 = QLabel(self.groupBox_screen_action)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(350, 70, 31, 31))
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.spinBox_zoom_time = QSpinBox(self.groupBox_screen_action)
        self.spinBox_zoom_time.setObjectName(u"spinBox_zoom_time")
        self.spinBox_zoom_time.setGeometry(QRect(380, 70, 111, 31))
        self.spinBox_zoom_time.setAlignment(Qt.AlignCenter)
        self.spinBox_zoom_time.setMinimum(1)
        self.spinBox_zoom_time.setMaximum(999)
        self.label_slide_time = QLabel(self.groupBox_screen_action)
        self.label_slide_time.setObjectName(u"label_slide_time")
        self.label_slide_time.setGeometry(QRect(500, 30, 31, 31))
        self.label_zoom_time = QLabel(self.groupBox_screen_action)
        self.label_zoom_time.setObjectName(u"label_zoom_time")
        self.label_zoom_time.setGeometry(QRect(500, 70, 31, 31))
        self.groupBox_fly = QGroupBox(Dialog_subtitle_action_edit)
        self.groupBox_fly.setObjectName(u"groupBox_fly")
        self.groupBox_fly.setGeometry(QRect(20, 110, 661, 121))
        self.label_32 = QLabel(self.groupBox_fly)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(180, 30, 31, 31))
        self.label_32.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_31 = QLabel(self.groupBox_fly)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(350, 30, 31, 31))
        self.label_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_target_altitude = QLineEdit(self.groupBox_fly)
        self.lineEdit_target_altitude.setObjectName(u"lineEdit_target_altitude")
        self.lineEdit_target_altitude.setGeometry(QRect(380, 30, 111, 31))
        self.label_33 = QLabel(self.groupBox_fly)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 30, 31, 31))
        self.label_33.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_target_latitude = QLineEdit(self.groupBox_fly)
        self.lineEdit_target_latitude.setObjectName(u"lineEdit_target_latitude")
        self.lineEdit_target_latitude.setGeometry(QRect(210, 30, 111, 31))
        self.lineEdit_target_longitude = QLineEdit(self.groupBox_fly)
        self.lineEdit_target_longitude.setObjectName(u"lineEdit_target_longitude")
        self.lineEdit_target_longitude.setGeometry(QRect(40, 30, 111, 31))
        self.label_42 = QLabel(self.groupBox_fly)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 80, 31, 31))
        self.label_42.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEdit_target_place_name = QLineEdit(self.groupBox_fly)
        self.lineEdit_target_place_name.setObjectName(u"lineEdit_target_place_name")
        self.lineEdit_target_place_name.setGeometry(QRect(40, 80, 451, 31))
        self.pushButton_get_position = QPushButton(self.groupBox_fly)
        self.pushButton_get_position.setObjectName(u"pushButton_get_position")
        self.pushButton_get_position.setGeometry(QRect(540, 30, 111, 81))
        self.groupBox_set_2d_3d_view = QGroupBox(Dialog_subtitle_action_edit)
        self.groupBox_set_2d_3d_view.setObjectName(u"groupBox_set_2d_3d_view")
        self.groupBox_set_2d_3d_view.setGeometry(QRect(360, 20, 321, 71))
        self.checkBox_2D_view = QCheckBox(self.groupBox_set_2d_3d_view)
        self.checkBox_2D_view.setObjectName(u"checkBox_2D_view")
        self.checkBox_2D_view.setGeometry(QRect(40, 30, 101, 31))
        self.checkBox_3D_view = QCheckBox(self.groupBox_set_2d_3d_view)
        self.checkBox_3D_view.setObjectName(u"checkBox_3D_view")
        self.checkBox_3D_view.setGeometry(QRect(200, 30, 101, 31))
        QWidget.setTabOrder(self.lineEdit_target_longitude, self.lineEdit_target_latitude)
        QWidget.setTabOrder(self.lineEdit_target_latitude, self.lineEdit_target_altitude)
        QWidget.setTabOrder(self.lineEdit_target_altitude, self.lineEdit_heading)
        QWidget.setTabOrder(self.lineEdit_heading, self.lineEdit_tilt)
        QWidget.setTabOrder(self.lineEdit_tilt, self.checkBox_2D_view)
        QWidget.setTabOrder(self.checkBox_2D_view, self.checkBox_3D_view)
        QWidget.setTabOrder(self.checkBox_3D_view, self.pushButton)

        self.retranslateUi(Dialog_subtitle_action_edit)

        QMetaObject.connectSlotsByName(Dialog_subtitle_action_edit)
    # setupUi

    def retranslateUi(self, Dialog_subtitle_action_edit):
        Dialog_subtitle_action_edit.setWindowTitle(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u5b57\u5e55\u5c5e\u6027\u7f16\u8f91", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u4fdd\u5b58", None))
        self.groupBox_suntitle_action.setTitle(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u98de\u884c\u8bbe\u7f6e", None))
        self.label_12.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u6a21\u5f0f", None))
        self.label_14.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u901f\u5ea6", None))
        self.label_info.setText("")
        self.groupBox_heading_tilt_view.setTitle(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u89c6\u89d2", None))
        self.lineEdit_tilt.setPlaceholderText("")
        self.label_38.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u503e\u659c", None))
        self.label_37.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u671d\u5411", None))
        self.lineEdit_heading.setPlaceholderText("")
        self.pushButton_get_heading_tilt.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u83b7\u53d6\u6570\u636e", None))
        self.groupBox_screen_action.setTitle(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u9f20\u6807\u79fb\u52a8/\u65cb\u8f6c/\u7f29\u653e", None))
        self.label_43.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u7ec8 Y", None))
        self.lineEdit_target_end_x.setPlaceholderText("")
        self.lineEdit_target_end_y.setPlaceholderText("")
        self.label_44.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u8d77 X", None))
        self.label_45.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u7ec8 X", None))
        self.lineEdit_target_start_y.setPlaceholderText("")
        self.label_46.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u8d77 Y", None))
        self.lineEdit_target_start_x.setPlaceholderText("")
        self.label_15.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u901f\u5ea6", None))
        self.pushButton_get_screen_coordination.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u83b7\u53d6\u5c4f\u5e55\u5750\u6807", None))
        self.label_16.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u6b21\u6570", None))
        self.label_slide_time.setText("")
        self.label_zoom_time.setText("")
        self.groupBox_fly.setTitle(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u98de\u884c\u76ee\u6807", None))
        self.label_32.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u7eac\u5ea6", None))
        self.label_31.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u6d77\u62d4", None))
        self.lineEdit_target_altitude.setPlaceholderText("")
        self.label_33.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u7ecf\u5ea6", None))
        self.lineEdit_target_latitude.setPlaceholderText("")
        self.lineEdit_target_longitude.setPlaceholderText("")
        self.label_42.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u5730\u540d", None))
        self.lineEdit_target_place_name.setPlaceholderText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u5730\u540d\u4e5f\u53ef\u4ee5\u8f93\u5165\u7ecf\u7eac\u5ea6", None))
        self.pushButton_get_position.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u83b7\u53d6\u5750\u6807", None))
        self.groupBox_set_2d_3d_view.setTitle(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u89c6\u56fe", None))
        self.checkBox_2D_view.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u5207\u63622D\u89c6\u56fe", None))
        self.checkBox_3D_view.setText(QCoreApplication.translate("Dialog_subtitle_action_edit", u"\u5207\u63623D\u89c6\u56fe", None))
    # retranslateUi

