# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'subtitle_prop_edit.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QDialog,
    QDoubleSpinBox, QGroupBox, QLabel, QPushButton,
    QSizePolicy, QWidget)

class Ui_Dialog_subtitle_edit(object):
    def setupUi(self, Dialog_subtitle_edit):
        if not Dialog_subtitle_edit.objectName():
            Dialog_subtitle_edit.setObjectName(u"Dialog_subtitle_edit")
        Dialog_subtitle_edit.setWindowModality(Qt.ApplicationModal)
        Dialog_subtitle_edit.resize(430, 500)
        Dialog_subtitle_edit.setMinimumSize(QSize(0, 0))
        Dialog_subtitle_edit.setMaximumSize(QSize(700, 750))
        self.pushButton = QPushButton(Dialog_subtitle_edit)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 440, 121, 31))
        self.groupBox_voice = QGroupBox(Dialog_subtitle_edit)
        self.groupBox_voice.setObjectName(u"groupBox_voice")
        self.groupBox_voice.setGeometry(QRect(20, 110, 391, 171))
        self.comboBox_voice_name = QComboBox(self.groupBox_voice)
        self.comboBox_voice_name.setObjectName(u"comboBox_voice_name")
        self.comboBox_voice_name.setGeometry(QRect(70, 30, 111, 31))
        self.comboBox_voice_role = QComboBox(self.groupBox_voice)
        self.comboBox_voice_role.setObjectName(u"comboBox_voice_role")
        self.comboBox_voice_role.setGeometry(QRect(70, 80, 111, 31))
        self.comboBox_voice_style = QComboBox(self.groupBox_voice)
        self.comboBox_voice_style.setObjectName(u"comboBox_voice_style")
        self.comboBox_voice_style.setGeometry(QRect(70, 130, 111, 31))
        self.label_39 = QLabel(self.groupBox_voice)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(30, 130, 31, 31))
        self.label_39.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_40 = QLabel(self.groupBox_voice)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(30, 30, 31, 31))
        self.label_40.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_41 = QLabel(self.groupBox_voice)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(30, 80, 31, 31))
        self.label_41.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.doubleSpinBox_voice_pitch = QDoubleSpinBox(self.groupBox_voice)
        self.doubleSpinBox_voice_pitch.setObjectName(u"doubleSpinBox_voice_pitch")
        self.doubleSpinBox_voice_pitch.setGeometry(QRect(260, 130, 111, 31))
        self.doubleSpinBox_voice_pitch.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_voice_pitch.setDecimals(1)
        self.doubleSpinBox_voice_pitch.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_voice_pitch.setValue(1.000000000000000)
        self.doubleSpinBox_voice_rate = QDoubleSpinBox(self.groupBox_voice)
        self.doubleSpinBox_voice_rate.setObjectName(u"doubleSpinBox_voice_rate")
        self.doubleSpinBox_voice_rate.setGeometry(QRect(260, 30, 111, 31))
        self.doubleSpinBox_voice_rate.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_voice_rate.setDecimals(1)
        self.doubleSpinBox_voice_rate.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_voice_rate.setValue(1.000000000000000)
        self.label_35 = QLabel(self.groupBox_voice)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(220, 80, 31, 31))
        self.label_35.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_34 = QLabel(self.groupBox_voice)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(220, 30, 31, 31))
        self.label_34.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_36 = QLabel(self.groupBox_voice)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(220, 130, 31, 31))
        self.label_36.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.doubleSpinBox_voice_volume = QDoubleSpinBox(self.groupBox_voice)
        self.doubleSpinBox_voice_volume.setObjectName(u"doubleSpinBox_voice_volume")
        self.doubleSpinBox_voice_volume.setGeometry(QRect(260, 80, 111, 31))
        self.doubleSpinBox_voice_volume.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_voice_volume.setDecimals(1)
        self.doubleSpinBox_voice_volume.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_voice_volume.setValue(1.000000000000000)
        self.label_info = QLabel(Dialog_subtitle_edit)
        self.label_info.setObjectName(u"label_info")
        self.label_info.setGeometry(QRect(20, 660, 661, 21))
        self.label_info.setAlignment(Qt.AlignCenter)
        self.groupBox_3 = QGroupBox(Dialog_subtitle_edit)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 20, 391, 71))
        self.doubleSpinBox_audio_time = QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_audio_time.setObjectName(u"doubleSpinBox_audio_time")
        self.doubleSpinBox_audio_time.setGeometry(QRect(70, 30, 111, 31))
        self.doubleSpinBox_audio_time.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_audio_time.setDecimals(1)
        self.doubleSpinBox_audio_time.setStepType(QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_audio_time.setValue(0.000000000000000)
        self.label_audio_time = QLabel(self.groupBox_3)
        self.label_audio_time.setObjectName(u"label_audio_time")
        self.label_audio_time.setGeometry(QRect(10, 30, 51, 31))
        self.label_audio_time.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.doubleSpinBox_ext_time = QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_ext_time.setObjectName(u"doubleSpinBox_ext_time")
        self.doubleSpinBox_ext_time.setGeometry(QRect(260, 30, 111, 31))
        self.doubleSpinBox_ext_time.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_ext_time.setDecimals(1)
        self.doubleSpinBox_ext_time.setStepType(QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_ext_time.setValue(0.000000000000000)
        self.label_audio_time_2 = QLabel(self.groupBox_3)
        self.label_audio_time_2.setObjectName(u"label_audio_time_2")
        self.label_audio_time_2.setGeometry(QRect(200, 30, 51, 31))
        self.label_audio_time_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.groupBox = QGroupBox(Dialog_subtitle_edit)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 300, 391, 111))
        self.comboBox_font_size = QComboBox(self.groupBox)
        self.comboBox_font_size.setObjectName(u"comboBox_font_size")
        self.comboBox_font_size.setGeometry(QRect(260, 20, 111, 31))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(220, 20, 31, 31))
        self.label_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 20, 31, 31))
        self.label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.comboBox_font = QComboBox(self.groupBox)
        self.comboBox_font.setObjectName(u"comboBox_font")
        self.comboBox_font.setGeometry(QRect(70, 20, 111, 31))
        self.comboBox_font_color = QComboBox(self.groupBox)
        self.comboBox_font_color.setObjectName(u"comboBox_font_color")
        self.comboBox_font_color.setGeometry(QRect(70, 70, 111, 31))
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 70, 31, 31))
        self.label_17.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        QWidget.setTabOrder(self.comboBox_voice_name, self.comboBox_voice_role)
        QWidget.setTabOrder(self.comboBox_voice_role, self.comboBox_voice_style)
        QWidget.setTabOrder(self.comboBox_voice_style, self.doubleSpinBox_voice_rate)
        QWidget.setTabOrder(self.doubleSpinBox_voice_rate, self.doubleSpinBox_voice_volume)
        QWidget.setTabOrder(self.doubleSpinBox_voice_volume, self.doubleSpinBox_voice_pitch)
        QWidget.setTabOrder(self.doubleSpinBox_voice_pitch, self.pushButton)

        self.retranslateUi(Dialog_subtitle_edit)

        QMetaObject.connectSlotsByName(Dialog_subtitle_edit)
    # setupUi

    def retranslateUi(self, Dialog_subtitle_edit):
        Dialog_subtitle_edit.setWindowTitle(QCoreApplication.translate("Dialog_subtitle_edit", u"\u5b57\u5e55\u5c5e\u6027\u7f16\u8f91", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u4fdd\u5b58", None))
        self.groupBox_voice.setTitle(QCoreApplication.translate("Dialog_subtitle_edit", u"\u914d\u97f3", None))
        self.label_39.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u98ce\u683c", None))
        self.label_40.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u97f3\u6e90", None))
        self.label_41.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u89d2\u8272", None))
        self.label_35.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u97f3\u91cf", None))
        self.label_34.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u8bed\u901f", None))
        self.label_36.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u97f3\u9ad8", None))
        self.label_info.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog_subtitle_edit", u"\u65f6\u957f", None))
        self.label_audio_time.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u8bed\u97f3\u65f6\u957f", None))
        self.label_audio_time_2.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u6269\u5c55\u65f6\u957f", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog_subtitle_edit", u"\u5b57\u4f53", None))
        self.label_11.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u5b57\u53f7", None))
        self.label_13.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u5b57\u4f53", None))
        self.label_17.setText(QCoreApplication.translate("Dialog_subtitle_edit", u"\u989c\u8272", None))
    # retranslateUi

